MAPBOX_TOKEN="pk.eyJ1IjoicmFkODBzYm14IiwiYSIcHk2bW9sZDcifQ.yj_dY1DnxPpxTnTyfEwfbg"
OPENWEATHER_API_KEY="e517ec7aecc657a3c578d26b6337c50d"
GOOGLE_WEATHER_API_KEY="AIzaSyCV2eB-zPUchxi5z24tsCXIrDvE1gb2I8Q"
